"""first tables

Revision ID: cc8ac5d2bfd7
Revises:
Create Date: 2025-02-01 19:18:29.311699

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from back.config import settings

# revision identifiers, used by Alembic.
revision: str = "cc8ac5d2bfd7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(f"CREATE SCHEMA IF NOT EXISTS {settings.DB_SCHEMA}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_permission_codes",
        sa.Column("lable", sa.Integer(), nullable=False),
        sa.Column("endpoint_name", sa.String(length=20), nullable=False),
        sa.Column("parameter", sa.String(length=10), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("lable"),
        sa.UniqueConstraint("endpoint_name", "parameter", name="perm_key"),
        sa.UniqueConstraint("lable"),
        schema=settings.DB_SCHEMA,
    )
    op.create_table(
        "api_token",
        sa.Column("service_name", sa.String(length=40), nullable=False),
        sa.Column("token_id", sa.String(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(), nullable=False),
        sa.Column("definition", sa.Text(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("token_id"),
        sa.UniqueConstraint("service_name"),
        schema=settings.DB_SCHEMA,
    )
    op.create_table(
        "api_permission_token",
        sa.Column("token_id", sa.String(), nullable=False),
        sa.Column("permission_codes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_codes"],
            [f"{settings.DB_SCHEMA}.api_permission_codes.lable"],
        ),
        sa.ForeignKeyConstraint(
            ["token_id"],
            [f"{settings.DB_SCHEMA}.api_token.token_id"],
        ),
        sa.PrimaryKeyConstraint("token_id", "permission_codes"),
        schema=settings.DB_SCHEMA,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Удаление схемы не буду добавлять."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("api_permission_token", schema=settings.DB_SCHEMA)
    op.drop_table("api_token", schema=settings.DB_SCHEMA)
    op.drop_table("api_permission_codes", schema=settings.DB_SCHEMA)
    # ### end Alembic commands ###
